# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keelo < Formula
  desc "A modular composition layer for Docker Compose."
  homepage "https://github.com/matansuliman/keelo"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matansuliman/keelo/releases/download/v0.6.0/keelo_0.6.0_darwin_amd64.tar.gz"
      sha256 "da37366697b2eb9580b0bc57fa7107b841dd17db9e2c6499707002334626a3d3"

      define_method(:install) do
        bin.install "keelo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matansuliman/keelo/releases/download/v0.6.0/keelo_0.6.0_darwin_arm64.tar.gz"
      sha256 "3f739817c9e46cbf015515273cbb3d2c7a265509002f8f818c6ce63b0d89292c"

      define_method(:install) do
        bin.install "keelo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matansuliman/keelo/releases/download/v0.6.0/keelo_0.6.0_linux_amd64.tar.gz"
      sha256 "0f2a680fb2086002c5f3ac9adfc9317d8ce775040a7e857cc0fd06f864abf495"
      define_method(:install) do
        bin.install "keelo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matansuliman/keelo/releases/download/v0.6.0/keelo_0.6.0_linux_arm64.tar.gz"
      sha256 "67f093c92bbf07d8c1da27afc4eea8c21b3cc066951376e82a0c084c42e2ba97"
      define_method(:install) do
        bin.install "keelo"
      end
    end
  end
end
